version: 2

jobs:
  build:
    working_directory: ~/service_monitor
    docker:
      - image: circleci/python:3.7
        environment:
          discovery.type: single-node
    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run the tests with tox
          command: tox
